### ISSUE TITLE
The protocol ArgumentFormatter implemented on several general types causes invalid props on react

### ISSUE THREAD

**Issue by mynomoto** [Vincit/venia#1]
I'm not sure about the mechanism but I did a quick test commenting the protocol and the implementations and the errors are gone. But of course args don't work that way :wink:

**Comment by macluck** [comment]
Hei, thanks for the issue! Which types were failing? Have you tried 0.1.0 -SNAPSHOT version? Some of the types are already fixed there.

**Comment by mynomoto** [comment]
I will try to get something more specific soon but my best guess at the moment is keywords. I will try the `0.1.1 -SNAPSHOT` and let you know. Also, I'm using reagent which  may be relevant to other people trying venia and getting the same problem.

**Comment by mynomoto** [comment]
The error is gone on `0.1.1- SNAPSHOT`, thanks!

**Comment by macluck** [comment]
Great!
