### ISSUE TITLE
mutations?

### ISSUE THREAD

**Issue by decoursin** [Vincit/venia#18]
Why is there no support for mutations?
```clojure
(venia/graphql-query {:venia/operation {:operation/type :mutation, :operation/name "venia"}, :venia/queries [[:add_human {:name :yoda, :home_planet "Dagobah"} [:human/id :human/home_planet :human/name]]]})

=> ExceptionInfo Invalid query data  clojure.core/ex-info (core.clj:4617)
In: [:venia/operation :operation/type] val: :mutation fails spec: :operation/type at: [:venia/operation :operation/type] predicate: #{:query}
:clojure.spec.alpha/spec  :venia/query-def
:clojure.spec.alpha/value  {:venia/operation {:operation/type :mutation, :operation/name "venia"}, :venia/queries [[:add_human {:name :yoda, :home_planet "Dagobah"} [:human/id :human/home_planet :human/name]]]}
declatests.core> 
```
However, it seems it would be supported based on this test: https://github.com/Vincit/venia/blob/0592a8165c9dcbdb366ec2479048ef6eec86d5db/test/venia/core_test.cljc#L261.

**Comment by macluck** [comment]
Hey, mutations are already supported indeed, but they are not released yet. I am going to push 0.2.4 release soon to clojars.

**Comment by decoursin** [comment]
Great, thank you so much!

**Comment by macluck** [comment]
Added in https://github.com/Vincit/venia/releases/tag/v0.2.4

**Comment by decoursin** [comment]
Are there any changes required for mutations beside :operation/type :mutation? I mean, to do a mutation, I just need to set the :operation/type to :mutation, right?

**Comment by decoursin** [comment]
Oh, I see you added docs already on the README, thanks, looks like that's it!
