### ISSUE TITLE
No support for field parameters beyond the root level

### ISSUE THREAD

**Issue by luchiniatwork** [Vincit/venia#8]
This works as expected with params `:id` and `:active` passed to `:employee`:

`(venia.core/graphql-query {:venia/queries [[:employee {:id 1 :active true} [:name :address [:friends [:name :email]]]]]})`

However, if one tries to add parameters to fields in the lower levels (i.e. `:preferNickname` below), Venia breaks:

`(venia.core/graphql-query {:venia/queries [[:employee {:id 1 :active true} [:name {:preferNickname 1} :address [:friends [:name :email]]]]]})`

**Comment by Wegi** [comment]
I also encountered this error. It always appears, when the field parameters are not used at the top or most bottom level.

This is the error encountered: `UnsupportedOperationException nth not supported on this type: Keyword  clojure.lang.RT.nthFrom`

**Comment by macluck** [comment]
Thanks, i will start working on fix some time soon! And sorry for delay, had a great 7-week vacation 😄

**Comment by macluck** [comment]
Will be added to 0.2.3 release

**Comment by AndreTheHunter** [comment]
This is still a problem. I'll create a new issue
